# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ltj/vivado/vivado_project/computer_org_lab09/computer_org_lab09.srcs/sources_1/ip/program/program.xci
# IP: The module: 'program' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ltj/vivado/vivado_project/computer_org_lab09/computer_org_lab09.srcs/sources_1/ip/program/program_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ltj/vivado/vivado_project/computer_org_lab09/computer_org_lab09.srcs/sources_1/ip/program/program.xci
# IP: The module: 'program' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ltj/vivado/vivado_project/computer_org_lab09/computer_org_lab09.srcs/sources_1/ip/program/program_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
